[package]
name = "checkupdates-external"
version = "0.1.0"
authors = ["Axel Navarro <navarroaxel@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.15"
itertools = "0.10.0"
libflate = "1.1.0"
reqwest = { version = "0.11.3", features = ["json", "gzip"] }
serde = { version = "1.0.126", features = ["derive"] }
serde-xml-rs = "0.4.1"
tokio = { version = "1.6.0", features = ["full"] }
