[package]
name = "checkupdates-external"
version = "0.1.0"
authors = ["Axel Navarro <navarroaxel@gmail.com>"]
edition = "2018"

[dependencies]
futures = "0.3.5"
libflate = "1.0.2"
serde = { version = "1.0.115", features = ["derive"] }
serde-xml-rs = "0.4.0"
reqwest = { version = "0.10.7", features = ["json", "gzip"] }
tokio = { version = "0.2.22", features = ["full"] }
