[package]
name = "teamviewer"
version = "0.1.0"
authors = ["Axel Navarro <navarroaxel@gmail.com>"]
edition = "2021"

[lib]

[dependencies]
aur = { path = "../aur" }
yum = { path = "../yum" }

reqwest = { version = "0.12.3", features = ["json", "gzip"] }
