[package]
name = "chrome"
version = "0.1.0"
authors = ["Axel Navarro <navarroaxel@gmail.com>"]

[lib]
edition = "2018"

[dependencies]
aur = { path = "../aur" }
yum = { path = "../yum" }

reqwest = { version = "0.11.3", features = ["json", "gzip"] }
